server:
  port: 9000
spring:
  application:
    name: ek-invoke
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10 #配置为5秒向服务器发送一次心跳请求
    lease-expiration-duration-in-seconds: 10 #多久没有发送心跳请求 就去除此客户端
    hostname: localhost
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: DEBUG